name: Push to Azure Web App

on:
  push:
    branches:
      - main # il workflow si attiva quando viene eseguito un push su main

jobs:
  build:
    runs-on: ubuntu-latest # esegue il workflow su un runner linux (macchina virtuale che esegue i job)

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3 # clona il repository github
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: | # esegue comandi su più righe
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerprova -f demo/dockerfile demo
          docker tag ${{ secrets.DOCKER_USERNAME }}/dockerprova ${{ secrets.DOCKER_USERNAME }}/dockerprova:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerprova:latest

  deploy:
     runs-on: ubuntu-latest
     needs: build

     steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dockerprova'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/dockerprova:latest